# Automatically generated by configure, do not edit
PREFIX=/Users/Shared/xbmc-depends/iphoneos9.2_armv7-target
libdir=${exec_prefix}/lib
shlibdir=/Users/Shared/xbmc-depends/iphoneos9.2_armv7-target/lib
incdir=/Users/Shared/xbmc-depends/iphoneos9.2_armv7-target/include/dvdnav
THREADLIB=-lpthread
BUILD_SHARED=no
BUILD_STATIC=yes
SHLIB_VERSION=4.2.1
SHLIB_MAJOR=4
CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
MAKE=make
CFLAGS=-O3  -O2 -g -D_DEBUG -Wall -fheinous-gnu-extensions -no-cpp-precomp -mcpu=cortex-a8 -mfpu=neon -ftree-vectorize -mfloat-abi=softfp -pipe -Wno-trigraphs -fpascal-strings -O3 -Wreturn-type -Wunused-variable -fmessage-length=0 -gdwarf-2 -arch armv7 -miphoneos-version-min=5.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -isystem /Users/Shared/xbmc-depends/iphoneos9.2_armv7-target/include -fheinous-gnu-extensions -no-cpp-precomp -mcpu=cortex-a8 -mfpu=neon -ftree-vectorize -mfloat-abi=softfp -pipe -Wno-trigraphs -fpascal-strings -O3 -Wreturn-type -Wunused-variable -fmessage-length=0 -gdwarf-2 -arch armv7 -miphoneos-version-min=5.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk -isystem /Users/Shared/xbmc-depends/iphoneos9.2_armv7-target/include -O3 -D_XBMC -UHAVE_DVDCSS_DVDCSS_H -D__DARWIN__ -I/Users/osx/Desktop/kodi/xbmc/lib/libdvd/libdvdnav/../includes
LDFLAGS= -L/Users/osx/Desktop/kodi/xbmc/lib/libdvd/libdvdnav/../libdvdread/obj
SHLDFLAGS=-dynamiclib -Wl,-single_module -Wl,-read_only_relocs,suppress
INSTALLSTRIP=-s
USEDEBUG=-g
DVDREAD_CFLAGS=
DVDREAD_LIBS=-ldvdread

SRC_PATH="/Users/osx/Desktop/kodi/xbmc/lib/libdvd/libdvdnav"
SRC_PATH_BARE=/Users/osx/Desktop/kodi/xbmc/lib/libdvd/libdvdnav

