SRCS  = CDDARipJob.cpp
SRCS += CDDARipper.cpp
SRCS += Encoder.cpp
SRCS += EncoderFFmpeg.cpp

LIB=cdrip.a

include /Users/osx/Desktop/kodi/xbmc/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
