INCLUDES+=-I/Users/osx/Desktop/kodi/xbmc/xbmc/cores/dvdplayer

SRCS  = DVDCodecUtils.cpp
SRCS += DVDFactoryCodec.cpp

LIB=	DVDCodecs.a

include /Users/osx/Desktop/kodi/xbmc/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))

