SRCS = DummyVideoPlayer.cpp
SRCS += FFmpeg.cpp
SRCS += DataCacheCore.cpp

LIB = cores.a

include /Users/osx/Desktop/kodi/xbmc/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
