SRCS  = HTTPPythonInvoker.cpp \
        HTTPPythonWsgiInvoker.cpp \

LIB = httprequesthandlers-python.a

INCLUDES += -I/Users/Shared/xbmc-depends/iphoneos9.2_armv7-target/include/python2.6

include /Users/osx/Desktop/kodi/xbmc/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
