SRCS  = PlayerCoreFactory.cpp
SRCS += PlayerSelectionRule.cpp

LIB = playercorefactory.a

include /Users/osx/Desktop/kodi/xbmc/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))

